package audit;


import java.util.Date;
import java.util.List;


/**
 * TblJobBase generated by MyEclipse - Hibernate Tools
 * 原来的表的主键fsn为Long型，排序按fsn降序排序，获取第一条记录就是当前步骤
 * 现在改为了String型，排序改用forderDate降序排序
 */

public class TblJobBase implements java.io.Serializable,Cloneable{
    /**
     * 状态：处理中
     */
    public static final int STATUS_HANDLING = 0;

    /**
     * 状态：已完成
     */
    public static final int STATUS_COMPLETE = 1;

    /**
     * 状态：异常
     */
    public static final int STATUS_EXCEPTION = 2;
    
    /**
     * 状态：撤回
     */
    public static final int STATUS_BACK = 3;
    
    /**
     * 状态：调整
     */
    public static final int STATUS_CHANGE = 4;

    // Fields    

     private String fsn;
     private Date fbeginTime;
     private Date fendTime;
     private Integer fjobStatus;
     private String ftaskId;
     private Integer fprocessId;
     private Integer fappId;
     private Date forderTime;
     private Integer fisAsynchronism;
     private Integer fsubmitOption;
     private Integer fishidden;
     private Integer fifOpen;
     private Date forderDate;// 这个时间，必须要有，用这个进行流转与记录的排序
     private String processName;
     
     private int isJobBase;
     
     private List miniJobs;
     
     public List getMiniJobs() {
		return miniJobs;
	}

	public void setMiniJobs(List miniJobs) {
		this.miniJobs = miniJobs;
	}

	public int getIsJobBase() {
		return isJobBase;
	}

	public void setIsJobBase(int isJobBase) {
		this.isJobBase = isJobBase;
	}

	public String getProcessName() {
		return processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public TblJobBase clone(){
     	try{
     		return (TblJobBase)super.clone();
     	}catch(Exception e){
     		e.printStackTrace();
     		return null;
     	}
  }
    // Constructors

    /** default constructor */
    public TblJobBase() {
    }

	/** minimal constructor */
    public TblJobBase(String fsn) {
        this.fsn = fsn;
    }
    
    /** full constructor */
    public TblJobBase(String fsn, Date fbeginTime, Date fendTime, Integer fjobStatus, String ftaskId, Integer fprocessId, Integer fappId, Date forderTime, Integer fisAsynchronism, Integer fsubmitOption, Integer fishidden, Integer fifOpen, Date forderDate) {
        this.fsn = fsn;
        this.fbeginTime = fbeginTime;
        this.fendTime = fendTime;
        this.fjobStatus = fjobStatus;
        this.ftaskId = ftaskId;
        this.fprocessId = fprocessId;
        this.fappId = fappId;
        this.forderTime = forderTime;
        this.fisAsynchronism = fisAsynchronism;
        this.fsubmitOption = fsubmitOption;
        this.fishidden = fishidden;
        this.fifOpen = fifOpen;
        this.forderDate = forderDate;
    }

   
    // Property accessors

    public String getFsn() {
        return this.fsn;
    }
    
    public void setFsn(String fsn) {
        this.fsn = fsn;
    }

    public Date getFbeginTime() {
        return this.fbeginTime;
    }
    
    public void setFbeginTime(Date fbeginTime) {
        this.fbeginTime = fbeginTime;
    }

    public Date getFendTime() {
        return this.fendTime;
    }
    
    public void setFendTime(Date fendTime) {
        this.fendTime = fendTime;
    }

    public Integer getFjobStatus() {
        return this.fjobStatus;
    }
    
    public void setFjobStatus(Integer fjobStatus) {
        this.fjobStatus = fjobStatus;
    }

    public String getFtaskId() {
        return this.ftaskId;
    }
    
    public void setFtaskId(String ftaskId) {
        this.ftaskId = ftaskId;
    }

    public Integer getFprocessId() {
        return this.fprocessId;
    }
    
    public void setFprocessId(Integer fprocessId) {
        this.fprocessId = fprocessId;
    }

    public Integer getFappId() {
        return this.fappId;
    }
    
    public void setFappId(Integer fappId) {
        this.fappId = fappId;
    }

    public Date getForderTime() {
        return this.forderTime;
    }
    
    public void setForderTime(Date forderTime) {
        this.forderTime = forderTime;
    }

    public Integer getFisAsynchronism() {
        return this.fisAsynchronism;
    }
    
    public void setFisAsynchronism(Integer fisAsynchronism) {
        this.fisAsynchronism = fisAsynchronism;
    }

    public Integer getFsubmitOption() {
        return this.fsubmitOption;
    }
    
    public void setFsubmitOption(Integer fsubmitOption) {
        this.fsubmitOption = fsubmitOption;
    }

    public Integer getFishidden() {
        return this.fishidden;
    }
    
    public void setFishidden(Integer fishidden) {
        this.fishidden = fishidden;
    }

    public Integer getFifOpen() {
        return this.fifOpen;
    }
    
    public void setFifOpen(Integer fifOpen) {
        this.fifOpen = fifOpen;
    }

    public Date getForderDate() {
        return this.forderDate;
    }
    
    public void setForderDate(Date forderDate) {
        this.forderDate = forderDate;
    }
   








}